version: "3"
services:
  server:
    image: graycube/docker-asvk:server2
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    
    ports:
      - "5000:5000"

  client:
    image: graycube/docker-asvk:server2

    network_mode: host

    depends_on:
      - server
